# Generated by Django 2.0.6 on 2018-07-17 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=100)),
                ('calories', models.CharField(max_length=20)),
                ('total_Carbs', models.CharField(max_length=20)),
                ('protein', models.CharField(max_length=20)),
                ('vitamin_A', models.IntegerField()),
                ('vitamin_C', models.IntegerField()),
                ('total_Fat', models.CharField(max_length=20)),
                ('calcium', models.IntegerField()),
                ('sodium', models.CharField(max_length=20)),
                ('potassium', models.CharField(max_length=20)),
                ('iron', models.IntegerField()),
                ('sugars', models.CharField(max_length=20)),
                ('cholesterol', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FoodQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=50)),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mynutriguide.FoodItem')),
            ],
        ),
        migrations.CreateModel(
            name='SevenMeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_name', models.CharField(max_length=25)),
            ],
        ),
    ]
