# Generated by Django 2.0.6 on 2018-07-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynutriguide', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='calcium',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='iron',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='vitamin_A',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='vitamin_C',
            field=models.CharField(max_length=20),
        ),
    ]
