# Generated by Django 2.0.6 on 2018-07-24 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mynutriguide', '0002_auto_20180717_1549'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SevenMeal',
            new_name='MealSelection',
        ),
        migrations.AddField(
            model_name='fooditem',
            name='meal_selection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mynutriguide.MealSelection'),
        ),
    ]
