# Generated by Django 2.0.6 on 2018-07-30 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynutriguide', '0003_auto_20180724_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompleteProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10)),
                ('age', models.DecimalField(decimal_places=1, max_digits=7)),
                ('weight', models.DecimalField(decimal_places=4, max_digits=7)),
                ('height', models.DecimalField(decimal_places=4, max_digits=7)),
            ],
        ),
    ]
