# Generated by Django 2.0.6 on 2018-08-02 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynutriguide', '0004_completeprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='BmiMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('measured_at', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='completeprofile',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='completeprofile',
            name='height',
            field=models.FloatField(help_text='Required. Enter height in feet(ft).'),
        ),
        migrations.AlterField(
            model_name='completeprofile',
            name='weight',
            field=models.FloatField(help_text='Required. Enter weight in Kilograms(Kg).'),
        ),
    ]
