# Generated by Django 2.0.6 on 2018-08-02 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mynutriguide', '0005_auto_20180802_1344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bmimeasurement',
            old_name='height',
            new_name='height_in_meters',
        ),
        migrations.RenameField(
            model_name='bmimeasurement',
            old_name='weight',
            new_name='weight_in_kg',
        ),
    ]
