# Generated by Django 2.0.6 on 2018-08-04 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynutriguide', '0006_auto_20180802_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='completeprofile',
            name='activity_factor',
            field=models.CharField(default=1.2, max_length=30),
            preserve_default=False,
        ),
    ]
