# Generated by Django 2.0.6 on 2018-08-04 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mynutriguide', '0007_completeprofile_activity_factor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BmiMeasurement',
        ),
        migrations.AddField(
            model_name='completeprofile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
